# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        MainWindow.setMinimumSize(QtCore.QSize(800, 450))
        MainWindow.setMaximumSize(QtCore.QSize(800, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/camel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Slovak, QtCore.QLocale.Slovakia))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 451))
        self.stackedWidget.setObjectName("stackedWidget")
        self.portal = QtWidgets.QWidget()
        self.portal.setObjectName("portal")
        self.home = QtWidgets.QCommandLinkButton(self.portal)
        self.home.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.home.setStyleSheet(":hover {\n"
"    border: none;\n"
"}")
        self.home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../assets/icons/left-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon1)
        self.home.setObjectName("home")
        self.label_7 = QtWidgets.QLabel(self.portal)
        self.label_7.setGeometry(QtCore.QRect(320, 10, 161, 31))
        self.label_7.setStyleSheet("font-family: \"Myanmar Text\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"")
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.portal)
        self.databaza = QtWidgets.QWidget()
        self.databaza.setObjectName("databaza")
        self.home_5 = QtWidgets.QCommandLinkButton(self.databaza)
        self.home_5.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.home_5.setStyleSheet(":hover {\n"
"    border: none;\n"
"}")
        self.home_5.setText("")
        self.home_5.setIcon(icon1)
        self.home_5.setObjectName("home_5")
        self.label_8 = QtWidgets.QLabel(self.databaza)
        self.label_8.setGeometry(QtCore.QRect(320, 10, 161, 31))
        self.label_8.setStyleSheet("font-family: \"Myanmar Text\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.databaza)
        self.cenotvorba = QtWidgets.QWidget()
        self.cenotvorba.setObjectName("cenotvorba")
        self.home_3 = QtWidgets.QCommandLinkButton(self.cenotvorba)
        self.home_3.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.home_3.setStyleSheet(":hover {\n"
"    border: none;\n"
"}")
        self.home_3.setText("")
        self.home_3.setIcon(icon1)
        self.home_3.setObjectName("home_3")
        self.label_9 = QtWidgets.QLabel(self.cenotvorba)
        self.label_9.setGeometry(QtCore.QRect(320, 10, 161, 31))
        self.label_9.setStyleSheet("font-family: \"Myanmar Text\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.cenotvorba)
        self.sklad = QtWidgets.QWidget()
        self.sklad.setObjectName("sklad")
        self.home_4 = QtWidgets.QCommandLinkButton(self.sklad)
        self.home_4.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.home_4.setStyleSheet(":hover {\n"
"    border: none;\n"
"}")
        self.home_4.setText("")
        self.home_4.setIcon(icon1)
        self.home_4.setObjectName("home_4")
        self.label_10 = QtWidgets.QLabel(self.sklad)
        self.label_10.setGeometry(QtCore.QRect(320, 10, 161, 31))
        self.label_10.setStyleSheet("font-family: \"Myanmar Text\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"")
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.sklad)
        self.statistika = QtWidgets.QWidget()
        self.statistika.setObjectName("statistika")
        self.home_2 = QtWidgets.QCommandLinkButton(self.statistika)
        self.home_2.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.home_2.setStyleSheet(":hover {\n"
"    border: none;\n"
"}")
        self.home_2.setText("")
        self.home_2.setIcon(icon1)
        self.home_2.setObjectName("home_2")
        self.label_11 = QtWidgets.QLabel(self.statistika)
        self.label_11.setGeometry(QtCore.QRect(320, 10, 161, 31))
        self.label_11.setStyleSheet("font-family: \"Myanmar Text\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"")
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.statistika)
        self.index = QtWidgets.QWidget()
        self.index.setObjectName("index")
        self.label_3 = QtWidgets.QLabel(self.index)
        self.label_3.setGeometry(QtCore.QRect(220, 270, 121, 31))
        self.label_3.setStyleSheet("font-family: \"Myanmar Text\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.index)
        self.label_2.setGeometry(QtCore.QRect(100, 270, 121, 31))
        self.label_2.setStyleSheet("font-family: \"Myanmar Text\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.index)
        self.label_4.setGeometry(QtCore.QRect(340, 270, 121, 31))
        self.label_4.setStyleSheet("font-family: \"Myanmar Text\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.index)
        self.pushButton.setGeometry(QtCore.QRect(120, 180, 80, 80))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background: rgb(0, 170, 255);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(10, 174, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 142, 213);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"    border-radius: 4px;\n"
"}")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../assets/icons/price-tag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.index)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 180, 80, 80))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: rgb(0, 170, 255);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(10, 174, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 142, 213);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"    border-radius: 4px;\n"
"}")
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../assets/icons/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.index)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 180, 80, 80))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background: rgb(0, 170, 255);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(10, 174, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 142, 213);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"    border-radius: 4px;\n"
"}")
        self.pushButton_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../assets/icons/locker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_6 = QtWidgets.QLabel(self.index)
        self.label_6.setGeometry(QtCore.QRect(580, 270, 121, 31))
        self.label_6.setStyleSheet("font-family: \"Myanmar Text\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.index)
        self.label.setGeometry(QtCore.QRect(360, 20, 81, 80))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap("../../assets/icons/camel.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.index)
        self.pushButton_5.setGeometry(QtCore.QRect(600, 180, 80, 80))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background: rgb(0, 170, 255);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(10, 174, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 142, 213);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"    border-radius: 4px;\n"
"}")
        self.pushButton_5.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../assets/icons/online-shop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.index)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 180, 80, 80))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background: rgb(0, 170, 255);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(10, 174, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 142, 213);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"    border-radius: 4px;\n"
"}")
        self.pushButton_4.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../assets/icons/shopping-bag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(self.index)
        self.label_5.setGeometry(QtCore.QRect(460, 270, 121, 51))
        self.label_5.setStyleSheet("QLabel {\n"
"    font-family: \"Myanmar Text\";\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    line-height: 80;\n"
"}\n"
"")
        self.label_5.setLineWidth(1)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.index)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Camels Infornation System"))
        self.label_7.setText(_translate("MainWindow", "PREDAJNÝ PORTÁL"))
        self.label_8.setText(_translate("MainWindow", "INTERNÁ DATABÁZA"))
        self.label_9.setText(_translate("MainWindow", "CENOTVORBA"))
        self.label_10.setText(_translate("MainWindow", "SKLAD"))
        self.label_11.setText(_translate("MainWindow", "ŠTATISTIKA"))
        self.label_3.setText(_translate("MainWindow", "ŠTATISTIKA"))
        self.label_2.setText(_translate("MainWindow", "CENOTVORBA"))
        self.label_4.setText(_translate("MainWindow", "SKLAD"))
        self.label_6.setText(_translate("MainWindow", "DATABÁZA"))
        self.label_5.setText(_translate("MainWindow", "PREDAJNÝ PORTÁL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
